-   name:   >
        Asegurarme que unos paquetes que me pidan 
        queden instalados si estoy en Redhat o derivados
    yum:
        name: "{{ item.key }}{{ '' if item.value is none else ('-' + item.value) }}"
        state: present
    loop: "{{ paquetes | dict2items }}"
    register: install
