-   name:   >
        Asegurarme que unos paquetes que me pidan 
        queden instalados si estoy en Debian o derivados
    apt:
        name: "{{ item.key }}{{ '' if item.value is none else ('=' + item.value) }}"
        state: present
    loop: "{{ paquetes | dict2items }}"
    register: install
    ignore_errors: True

-   name:   >
        Asegurarme que unos paquetes que me pidan 
        queden instalados si estoy en Debian o derivados
    apt:
        name: "{{ item.key }}"
        state: present
    loop: "{{ paquetes | dict2items }}"
    register: install
    when: install is failed


# condicion ? valor-si-true : valor-si-false
# valor-si-true if condicion else valor-si-false