nginx_version: 1.14.0

apps_to_deploy:
    -   name: app1
        repo: https://github.com/IvanciniGT/webEjemploAnsible
        version: master
        port: 80
        serverName: 172.31.38.202
#    -   name: app2
#        repo: https://github.com/IvanciniGT/webEjemploAnsible
#        version: master
#        port: 80
#        serverName: app2.prod
#        test:
#            endpoint: index.html
#            status_code: 200
#            test_content: "algun texto que se devuelva al hacer esa peticion"
    #app1:
    #    repo: https://github.com/ansible/ansible-examples.git
    #    version: master