# Dejar un servidor nginx funcionando en un entorno

-   hosts: all

    gather_facts: True
    
    vars: {}
    
    pre_tasks:
        -   include_tasks: "pretasks/playbook.yaml"
            
    tasks:
        -   include_tasks: "tasks/playbook.yaml"

    post_tasks:
        -   include_tasks: "posttasks/playbook.yaml"

    handlers:
        -   include_tasks: "handlers/playbook.yaml"
