# Dejar un servidor nginx funcionando en un entorno

-   hosts: all

    gather_facts: True
    become: True
    
    vars:   # Las variables las voy a quitar de aqui más adelante!!!
        nginx_version: 1.14.0
        SUPPORTED_OS: 
            - Debian
            - Redhat
        DEPENDENCIES:
            git: ~
            
    pre_tasks:
        -   include_tasks: "pretasks/main.yaml"
            
    tasks:
        -   include_tasks: "tasks/main.yaml"

    post_tasks:
        -   include_tasks: "posttasks/main.yaml"

    handlers:
        -   include_tasks: "handlers/main.yaml"
